version: '3'
services:
    config:
        build:
            context: ./gobots-config-server
            dockerfile: Dockerfile
        ports:
            - '9090:9090'
    eureka:
        build:
            context: ./gobots-eureka-server
            dockerfile: Dockerfile
        ports:
            - '9091:9091'
        restart: on-failure
        depends_on:
            - config
        links:
            - config
    zuul:
        build:
            context: ./gobots-zuul-server
            dockerfile: Dockerfile
        ports:
            - '9092:9092'
        restart: on-failure
        depends_on:
            - config
            - eureka
        links:
            - config
            - eureka
    suggestion:
        build:
            context: ./gobots-suggestion-server
            dockerfile: Dockerfile
        ports:
            - '9093:9093'
        restart: on-failure
        depends_on:
            - config
            - eureka
            - zuul
        links:
            - config
            - eureka
            - zuul
